// GENERATED by scripts/generate.ts — edit scripts/templates/opencode/plugins/devkit.js instead
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const extractAndStripFrontmatter = (content) => {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { content };
  return { content: match[2] };
};

let _bootstrapCache = undefined;

export const DevkitPlugin = async () => {
  const skillsDir = path.resolve(__dirname, '../../skills');

  const getBootstrapContent = () => {
    if (_bootstrapCache !== undefined) return _bootstrapCache;
    const skillPath = path.join(skillsDir, '{{bootstrapSkill}}', 'SKILL.md');
    if (!fs.existsSync(skillPath)) { _bootstrapCache = null; return null; }
    const { content } = extractAndStripFrontmatter(fs.readFileSync(skillPath, 'utf8'));
    const toolMapping = `**Tool Mapping for OpenCode:**
- Invoke a skill -> OpenCode's native \`skill\` tool
- Read files -> \`read\`; create/edit/delete -> \`apply_patch\`; run shell -> \`bash\`
- Search -> \`grep\`, \`glob\`; fetch a URL -> \`webfetch\``;
    _bootstrapCache = `<EXTREMELY_IMPORTANT>
You have {{pluginName}} skills.

The {{bootstrapSkill}} skill content is included below. It is ALREADY LOADED.

${content}

${toolMapping}
</EXTREMELY_IMPORTANT>`;
    return _bootstrapCache;
  };

  return {
    config: async (config) => {
      config.skills = config.skills || {};
      config.skills.paths = config.skills.paths || [];
      if (!config.skills.paths.includes(skillsDir)) config.skills.paths.push(skillsDir);
    },
    'experimental.chat.messages.transform': async (_input, output) => {
      const bootstrap = getBootstrapContent();
      if (!bootstrap || !output.messages.length) return;
      const firstUser = output.messages.find(m => m.info.role === 'user');
      if (!firstUser || !firstUser.parts.length) return;
      if (firstUser.parts.some(p => p.type === 'text' && p.text.includes('You have {{pluginName}} skills.'))) return;
      const ref = firstUser.parts[0];
      firstUser.parts.unshift({ ...ref, type: 'text', text: bootstrap });
    }
  };
};
