// GENERATED by scripts/generate.ts — edit scripts/templates/pi/extensions/devkit.ts instead
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const EXTREMELY_IMPORTANT_MARKER = "<EXTREMELY_IMPORTANT>";
const BOOTSTRAP_MARKER = "{{pluginName}}:{{bootstrapSkill}} bootstrap for pi";

const extensionDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(extensionDir, "../..");
const skillsDir = resolve(packageRoot, "skills");
const bootstrapSkillPath = resolve(skillsDir, "{{bootstrapSkill}}", "SKILL.md");

let cachedBootstrap: string | null | undefined;

export default function devkitPiExtension(pi: ExtensionAPI) {
  let injectBootstrap = true;
  pi.on("resources_discover", async () => ({ skillPaths: [skillsDir] }));
  pi.on("session_start", async () => {
    injectBootstrap = true;
  });
  pi.on("session_compact", async () => {
    injectBootstrap = true;
  });
  pi.on("agent_end", async () => {
    injectBootstrap = false;
  });
  pi.on("context", async (event) => {
    if (!injectBootstrap) return;
    if (event.messages.some(messageContainsBootstrap)) return;
    const bootstrap = getBootstrapContent();
    if (!bootstrap) return;
    const msg = {
      role: "user" as const,
      content: [{ type: "text" as const, text: bootstrap }],
      timestamp: Date.now(),
    };
    const at = firstNonCompactionSummaryIndex(event.messages);
    return {
      messages: [
        ...event.messages.slice(0, at),
        msg,
        ...event.messages.slice(at),
      ],
    };
  });
}

function getBootstrapContent(): string | null {
  if (cachedBootstrap !== undefined) return cachedBootstrap;
  try {
    const body = stripFrontmatter(readFileSync(bootstrapSkillPath, "utf8"));
    cachedBootstrap = `${EXTREMELY_IMPORTANT_MARKER}
${BOOTSTRAP_MARKER}

You have {{pluginName}} skills. The {{bootstrapSkill}} skill content is included below and is already loaded for this Pi session. Follow it now.

${body}

${piToolMapping()}
</EXTREMELY_IMPORTANT>`;
    return cachedBootstrap;
  } catch {
    cachedBootstrap = null;
    return null;
  }
}

function stripFrontmatter(content: string): string {
  const m = content.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/);
  return (m ? m[1] : content).trim();
}

function piToolMapping(): string {
  return `## Pi tool mapping

When a {{pluginName}} instruction says to invoke a skill, use Pi's native skill system: load the relevant SKILL.md with \`read\`. Pi's coding tools are lowercase: \`read\`, \`write\`, \`edit\`, \`bash\`, plus optional \`grep\`, \`find\`, \`ls\`.`;
}

function messageContainsBootstrap(message: unknown): boolean {
  const content = (message as { content?: unknown }).content;
  if (typeof content === "string") return content.includes(BOOTSTRAP_MARKER);
  if (!Array.isArray(content)) return false;
  return content.some((part) =>
    part && typeof part === "object" &&
    (part as { type?: unknown }).type === "text" &&
    typeof (part as { text?: unknown }).text === "string" &&
    (part as { text: string }).text.includes(BOOTSTRAP_MARKER)
  );
}

function firstNonCompactionSummaryIndex(messages: unknown[]): number {
  let i = 0;
  while (
    (messages[i] as { role?: unknown } | undefined)?.role ===
      "compactionSummary"
  ) i += 1;
  return i;
}
