import type { GeneratedFile, MarketplaceConfig } from "./types.ts";

const GEN =
  "GENERATED by scripts/generate.ts — edit marketplace.config.ts instead";

function json(obj: unknown): string {
  return JSON.stringify({ _generated: GEN, ...obj as object }, null, 2) + "\n";
}

export function renderJson(c: MarketplaceConfig): GeneratedFile[] {
  const author = { name: c.owner.name, email: c.owner.email };
  const base = {
    name: c.plugin.name,
    version: c.plugin.version,
    description: c.plugin.description,
    author,
    homepage: c.plugin.homepage,
    repository: c.plugin.repository,
    license: c.plugin.license,
    keywords: c.plugin.keywords,
  };
  const iface = {
    displayName: c.interface.displayName,
    shortDescription: c.plugin.description,
    longDescription: c.plugin.description,
    developerName: c.owner.name,
    category: c.interface.category,
    capabilities: ["Interactive", "Read", "Write"],
    websiteURL: c.plugin.homepage,
    brandColor: c.interface.brandColor,
    composerIcon: c.interface.composerIcon,
    logo: c.interface.logo,
  };

  return [
    {
      path: ".claude-plugin/marketplace.json",
      content: json({
        name: c.marketplace.name,
        description: c.marketplace.description,
        owner: author,
        plugins: [{
          name: c.plugin.name,
          description: c.plugin.description,
          version: c.plugin.version,
          source: "./",
          author,
        }],
      }),
    },
    { path: ".claude-plugin/plugin.json", content: json(base) },
    {
      path: ".codex-plugin/plugin.json",
      content: json({
        ...base,
        skills: "./skills/",
        hooks: "./hooks/hooks-codex.json",
        interface: iface,
      }),
    },
    {
      path: ".cursor-plugin/plugin.json",
      content: json({
        ...base,
        displayName: c.interface.displayName,
        skills: "./skills/",
        hooks: "./hooks/hooks-cursor.json",
      }),
    },
    {
      path: ".kimi-plugin/plugin.json",
      content: json({
        ...base,
        skills: "./skills/",
        sessionStart: { skill: c.bootstrapSkill },
        interface: iface,
      }),
    },
    {
      path: "gemini-extension.json",
      content: json({
        name: c.plugin.name,
        description: c.plugin.description,
        version: c.plugin.version,
        contextFileName: "GEMINI.md",
      }),
    },
    {
      path: "package.json",
      content: json({
        name: c.plugin.name,
        version: c.plugin.version,
        description: c.plugin.description,
        license: c.plugin.license,
        author: `${c.owner.name} <${c.owner.email}>`,
        homepage: c.plugin.homepage,
        repository: c.plugin.repository,
      }),
    },
  ];
}
